# **What is NumPy?**
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

**Why Use NumPy?**


In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.





**Why is NumPy Faster Than Lists?**


NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

**Which Language is NumPy written in?**


NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

In [5]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


**Checking NumPy Version**

The version string is stored under __version__ attribute.

In [ ]:
#How to check version of numpy
print(np.__version__)

2.0.2


In [21]:
# Zeroes and ones
arr=np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [22]:
#Ones
arr=np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [23]:
#Matrix
arr=np.matrix(np.ones((4,4)))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [25]:
# Random
arr=np.random.random((2,3))
print(arr)


[[0.29634709 0.96704688 0.95430398]
 [0.61896155 0.89072307 0.47845293]]


In [26]:
arr=np.random.randint(1,10,(2,3))
print(arr)

[[3 6 3]
 [4 9 6]]


# **Create a NumPy ndarray Object**
NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

In [ ]:
#Example
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#Example
#Use a tuple to create a NumPy array:



arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


# **Dimensions in Arrays**
A dimension in arrays is one level of array depth (nested arrays).

**0-D Arrays**

0-D arrays, or Scalars, are the elements in an array.

Each value in is a 0-D array

In [ ]:
#Example
#Create a 0-D array with value 42
arr = np.array(42)
print(arr)

42


**1-D Arrays**

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [ ]:
#Example
#Create a 1-D array containing the values 1,2,3,4,5:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


**2-D Arrays**

An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.



In [ ]:
#Example
#Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


**3-D arrays**

An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [ ]:
#Example
#Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# **Check Number of Dimensions?**
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [ ]:
#Check the dimensions of the array
a= np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


**Higher Dimensional Arrays**

An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument

In [ ]:
#Example
#Create an array with 5 dimensions and verify that it has 5 dimensions:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# **NumPy Array Indexing**

**Access Array Elements**

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [ ]:
#ExampleGet your own Python Server
#Get the first element from the following array:
arr = np.array([1, 2, 3, 4])

print(arr[0])


1


In [ ]:
#Example
#Get the second element from the following array.
arr=np.array([1,2,3,4,5])
print(arr[1])

2


In [ ]:
#Example
#Get third and fourth elements from the following array and add them.
arr=np.array([1,2,3,4,5])
print(arr[2]+arr[3])

7


**Access 2-D Arrays**

To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [ ]:
#Example
#Access the element on the first row, second column:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row:',arr[0,1])

2nd element on 1st row: 2


In [ ]:
#Example
#Access the element on the 2nd row, 5th column:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('5th element on 2nd row:',arr[1,4])


5th element on 2nd row: 10


**Access 3-D Arrays**

To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [ ]:
#Example
#Access the third element of the second array of the first array:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


In [ ]:
#Example
#Print the last element from the 2nd dim:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[1,1,2])

12


# **NumPy Array Slicing**
**Slicing arrays**

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [ ]:
#ExampleGet your own Python Server
#Slice elements from index 1 to index 5 from the following array
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [ ]:
#Example
#Slice elements from index 4 to the end of the array:
arr=np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


In [ ]:
#Example
#Slice elements from the beginning to index 4 (not included):
arr=np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


**Negative Slicing**

Use the minus operator to refer to an index from the end:

In [ ]:
#Example
#Slice from the index 3 from the end to index 1 from the end:
arr=np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


**STEP**

Use the step value to determine the step of the slicing:

STEP
Use the step value to determine the step of the slicing:

In [ ]:
#Example
#Return every other element from index 1 to index 5:
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [ ]:
#Example
#Return every other element from the entire array:
arr=np.array([1,2,3,4,5,6,7])
print(arr[::2])


[1 3 5 7]


**Slicing 2-D Arrays**

In [ ]:
#Example
#From the second element, slice elements from index 1 to index 4 (not included):
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [ ]:
#Example
#From both elements, return index 2:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[:,2])


[3 8]


In [ ]:
#Example
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[:,1:4])

[[2 3 4]
 [7 8 9]]


# ** Numpy Data Types**

**Data Types in Python**

By default Python have these data types:

strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"

integer - used to represent integer numbers. e.g. -1, -2, -3

float - used to represent real numbers. e.g. 1.2, 42.42

boolean - used to represent True or False.

complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j


**Data Types in NumPy**

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )


**Checking the Data Type of an Array**

The NumPy array object has a property called dtype that returns the data type of the array:

In [ ]:
#ExampleGet your own Python Server
#Get the data type of an array object:
arr=np.array([1,2,3,55,44,5])
print(arr.dtype)

int64


In [ ]:
#Example
#Get the data type of an array containing strings:
arr=np.array(['apple','banana','cherry'])
print(arr.dtype)

<U6


# **Creating Arrays With a Defined Data Type**
We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:

In [ ]:
#Example
#Create an array with data type string:
arr=np.array([1,2,3,4],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
#xample
#Create an array with data type 4 bytes integer:
arr=np.array([1,2,3,4],dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


**Converting Data Type on Existing Arrays**

The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [ ]:
#Change data type from float to integer by using 'i' as parameter value:
arr=np.array([1.1,2.1,3.1])
newarr=arr.astype('i') # Here we can also use int
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
#Example
#Change data type from integer to boolean:
arr=np.array([1,0,3])
newarr=arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


# **NumPy Array Copy vs View**

**The Difference Between Copy and View**

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

**COPY:**


In [ ]:
#ExampleGet your own Python Server
#Make a copy, change the original array, and display both arrays:
arr=np.array([1,2,3,4,5])
x=arr.copy()
x[0]=45
print(x)
print(arr)

[45  2  3  4  5]
[1 2 3 4 5]


**View**

In [ ]:
#Example
#Make a view, change the original array, and display both arrays:
arr=np.array([1,2,3,4,5])
x=arr.view()
x[0]=45
print(x)
print(arr)

[45  2  3  4  5]
[45  2  3  4  5]


**Check if Array Owns its Data**

As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [ ]:
#Example
#Print the value of the base attribute to check if an array owns it's data or not:
arr=np.array([1,2,3,4,5,6,88])
x=arr.copy()
y=arr.view()
print(x.base)
print(y.base)

None
[ 1  2  3  4  5  6 88]


**The copy returns None.**


**The view returns the original array.**



# **NumPy Array Shape**

**Shape of an Array**

The shape of an array is the number of elements in each dimension.

**Get the Shape of an Array**

NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [ ]:
# ExampleGet your own Python Server
# Print the shape of a 2-D array:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr.shape)

(2, 5)


In [ ]:
arr=np.array([[[1,2,3,4],[5,6,4,5]],[[44,5,55,66],[44,78,9,5,]]])
print(arr.shape)

(2, 2, 4)


In [ ]:
#Example
#Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print('shape of array:',arr.shape)

[[[[[1 2 3 4]]]]]
shape of array: (1, 1, 1, 1, 4)


# **NumPy Array Reshaping**
**Reshaping arrays**

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

**Reshape From 1-D to 2-D**

In [ ]:
#ExampleGet your own Python Server
#Convert the following 1-D array with 12 elements into a 2-D array.
#The outermost dimension will have 4 arrays, each with 3 elements:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr.reshape(5,2))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr.reshape(2,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


**Reshape From 1-D to 3-D**

In [ ]:
#Example
#Convert the following 1-D array with 12 elements into a 3-D array.
#The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


**Returns Copy or View**

In [ ]:
#Example
#Check if the returned array is a copy or a view:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,4).base)


[1 2 3 4 5 6 7 8]


**Unknown Dimension**

You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [ ]:
#Example
#Convert 1D array with 8 elements to 3D array with 2x2 elements
arr=np.array([1,2,3,4,5,6,7,8])
newarr=arr.reshape(2,2,-1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


**Flattening the arrays**

Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [ ]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.reshape(-1))

[1 2 3 4 5 6 7 8]


In [ ]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.flatten())

[1 2 3 4 5 6 7 8]


In [ ]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.ravel())

[1 2 3 4 5 6 7 8]


# ***NumPy Array Iterating***
**Iterating Arrays**

Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a 1-D array it will go through each element one by one.

In [ ]:
#ExampleGet your own Python Server
#Iterate on the elements of the following 1-D array:
arr=np.array([1,2,3,4,5,6,5,55,77])
for i in arr:
  print(i)

1
2
3
4
5
6
5
55
77


In [ ]:
# Using 2-D array
arr=np.array([[1,2,3,4],[5,6,7,8,]])
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6
7
8


In [ ]:
# using 3-D array
arr=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


**Iterating Arrays Using nditer()**

The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

Iterating on Each Scalar Element
In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

In [ ]:
arr=np.array([[55,63,88,74],[852,33,325,44]])
for x in np.nditer(arr):
  print(x)

55
63
88
74
852
33
325
44


**Iterating With Different Step Size**
We can use filtering and followed by iteration.

In [ ]:
arr=np.array([[55,63,88,74],[852,33,325,44]])
for x in np.nditer(arr[:,::2]):
  print(x)

55
88
852
325


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:,::2]):
  print(x)

1
3
5
7


**Enumerated Iteration Using ndenumerate()**

Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [ ]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [ ]:

arr = np.array(['a', 'b', 'c'])
for x in arr:
  print('Hello ' + x)

Hello a
Hello b
Hello c


# **NumPy Joining Array**
**Joining NumPy Arrays**

Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [ ]:
arr=np.array([1,2,3,5])
arr1=np.array([4,5,6,7])
arr2=np.concatenate((arr,arr1))
print(arr2)

[1 2 3 5 4 5 6 7]


In [ ]:
arr=np.array([[1,2,3,5],[44,5,55,66]])
arr1=np.array([[4,5,6,7],[11,12,36,55]])
arr2=np.concatenate((arr,arr1),axis=1)
print(arr2)


[[ 1  2  3  5  4  5  6  7]
 [44  5 55 66 11 12 36 55]]


In [ ]:
arr=np.array([[1,2,3,5],[44,5,55,66]])
arr1=np.array([[4,5,6,7],[11,12,36,55]])
arr2=np.concatenate((arr,arr1),axis=0)
print(arr2)


[[ 1  2  3  5]
 [44  5 55 66]
 [ 4  5  6  7]
 [11 12 36 55]]


**Joining Arrays Using Stack Functions**

Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [ ]:
#Using cocentenate using stack
arr=np.array([1,2,3,4])
aee=np.array([5,6,7,8])
arr1=np.stack((arr,aee),axis=1)
print(arr1)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [ ]:
#Using hstack
print(np.hstack((arr,aee)))

[1 2 3 4 5 6 7 8]


In [ ]:
#using vstack
print(np.vstack((arr,aee)))

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#Using dtsck
print(np.dstack((arr,aee)))

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


# **NumPy Splitting Array**

**Splitting NumPy Arrays**

Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.



In [ ]:
#Example
#Split the array in 3 parts:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(np.array_split(arr,3))

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [ ]:
#Example
#Split the array in 4 parts:

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


**Split Into Arrays**

The return value of the array_split() method is a list containing each of the split as an array.

If you split an array into 3 arrays, you can access them from the result just like any array element:

In [ ]:
#Access the splitted arrays:
arr=np.array([1,2,3,4,5,6,7,8,9])
newarr=np.array_split(arr,3)
print(newarr[0])
print(newarr[1])
print(newarr[2])


[1 2 3]
[4 5 6]
[7 8 9]


In [ ]:
#Split the 2-D array into three 2-D arrays.
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr=np.array_split(arr,3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:
#Use the hsplit() method to split the 2-D array into three 2-D arrays along columns.
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr=np.hsplit(arr,3)
print(newarr)



[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr=np.vsplit(arr,3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


# **NumPy Searching Arrays**

**Searching Arrays**

You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [ ]:
#Find the indexes where the value is 4:
arr=np.array([1,2,3,4,5,6])
x=np.where(arr==4)
print(x)

(array([3]),)


In [ ]:
# find the even value in the array
arr=np.array([11,12,33,44,66,88])
x=np.where(arr%2==0)
print(x)

(array([1, 3, 4, 5]),)


In [6]:
# Find the odd element in the array
arr=np.array([11,12,33,44,66,88])
x=np.where(arr%2==1)
print(x)

(array([0, 2]),)


**Search Sorted**

There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

The searchsorted() method is assumed to be used on sorted arrays.





In [8]:
#Example
# Find the indexes where the value 5 should be inserted:
arr=np.array([6,7,8,9])
print(np.searchsorted(arr,5))


0


**Search From the Right Side**

By default the left most index is returned, but we can give side='right' to return the right most index instead.

In [9]:
#Example
# Find the indexes where the value 5 should be inserted:
arr=np.array([6,7,8,9])
print(np.searchsorted(arr,5,side='right'))

0


**Multiple Values**

To search for more than one value, use an array with the specified values.

In [11]:
#Example
#Find the indexes where the values 2, 4, and 6 should be inserted:
arr=np.array([1,3,5,7])
print(np.searchsorted(arr,[2,4,6]))

[1 2 3]


# ***NumPy Sorting Arrays***

**Sorting Arrays**

Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [12]:
#Example
#Sort the array
arr=np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [13]:
#Example
#Sort the array alphabetically:
arr=np.array(['banana','cherry','apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [14]:
#Example
#Sort the array bollean
arr=np.array([True,False,True])
print(np.sort(arr))

[False  True  True]


**Sorting a 2-D Array**

If you use the sort() method on a 2-D array, both arrays will be sorted:

In [15]:
#Example
#Sort a 2-D array:


arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


** Broadcasting**

Allows operations on arrays of different shapes.

In [27]:
arr=np.array([1,2,3,4,5])
print(arr+2)

[3 4 5 6 7]
